create database if not exists home_inventory;
use home_inventory;
CREATE TABLE IF NOT EXISTS CATEGORY (
    CATEGORY_KEY INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE
)
;
CREATE TABLE IF NOT EXISTS UNIT (
    UNIT_KEY INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE
)
;
CREATE TABLE IF NOT EXISTS ITEM (
    ITEM_KEY INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    MAX INT UNSIGNED NOT NULL,
    CATEGORY_KEY INT UNSIGNED NOT NULL,
    FOREIGN KEY (CATEGORY_KEY)
        REFERENCES CATEGORY (CATEGORY_KEY)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIT_KEY INT UNSIGNED NOT NULL,
    FOREIGN KEY (UNIT_KEY)
        REFERENCES UNIT (UNIT_KEY)
        ON UPDATE CASCADE ON DELETE RESTRICT
)
